#!/usr/bin/env python3
"""Pull the firmware's real menus out of the build, as list fixtures.

    python extract-lists.py > lists.json
    python extract-lists.py --js            # ready to paste

Run from anywhere: with no argument it reads the checkout it is sitting in,
which is the whole reason the lens lives in the firmware tree. Name a different
checkout to read that one instead.

Laying out a list row against "Row one / Row two / Row three" tells you very
little: real menu text is longer, wraps differently, and carries icon ids your
row layout branches on. This reads the menus the firmware actually builds —
their order, their text, and the icon each item declares — so the preview shows
what the player will.

Three files carry it all:

  apps-ipod/lang/english.lang   LANG_* -> the English string
  apps-ipod/**/*.c              MENUITEM_* items and MAKE_MENU trees
  apps-ipod/settings/*.c        the LANG_* a MENUITEM_SETTING resolves through

Nothing here is compiled or executed — it is a read of the source. Where an
item's text is decided at runtime (MENUITEM_*_DYNTEXT) it is emitted with the
name the firmware gives it and a "dynamic" flag, because a fixture that guesses
would be worse than one that admits it.
"""

import argparse
import json
import os
import re
import sys

# tools/theme-lens/extract-lists.py -> the checkout root, two directories up.
# Derived from __file__ rather than the working directory so the script can be
# run from anywhere.
DEFAULT_FIRMWARE = os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))

# First line of the generated block, and what --embed finds the old one by. One
# constant because the two have to agree: when they did not, --embed failed to
# find the block it had written itself and appended a second one, and two
# `const FIRMWARE_LISTS` in a row is a syntax error that kills the whole page.
#
# Deliberately no directory in it. This script has moved once already, and a
# path here would go stale the next time in exactly that way.
BLOCK_MARKER = "/* Generated by extract-lists.py"

# enum current_activity, apps-ipod/system/activity.h. A skin ABI: the numbers
# are what %cs compares against.
ACTIVITY = {
    "MAINMENU": 1, "SETTINGS": 6, "CONTEXTMENU": 15, "SYSTEMSCREEN": 16,
    "SHORTCUTSMENU": 19, "TIMEDATESCREEN": 17, "BOOKMARKSLIST": 18,
}

# enum themable_icons, apps-ipod/draw/icon.h. Icon_Last_Themeable is where the
# theme's own iconset stops and the viewers iconset begins.
ICON_NAMES = [
    "Icon_Audio", "Icon_Folder", "Icon_Playlist", "Icon_Cursor", "Icon_Wps",
    "Icon_Firmware", "Icon_Font", "Icon_Language", "Icon_Config", "Icon_Plugin",
    "Icon_Bookmark", "Icon_Preset", "Icon_Queued", "Icon_Moving", "Icon_Keyboard",
    "Icon_Reverse_Cursor", "Icon_Questionmark", "Icon_Menu_setting",
    "Icon_Menu_functioncall", "Icon_Submenu", "Icon_Submenu_Entered",
    "Icon_Recording", "Icon_Voice", "Icon_General_settings_menu", "Icon_System_menu",
    "Icon_Playback_menu", "Icon_Display_menu", "Icon_Remote_Display_menu",
    "Icon_Radio_screen", "Icon_file_view_menu", "Icon_EQ", "Icon_Rockbox",
    "Icon_Last_Themeable",
]
ICONS = {name: i for i, name in enumerate(ICON_NAMES)}
ICONS["Icon_NOICON"] = -1
ICONS["NOICON"] = -1


# Items whose text is decided at runtime, where the firmware only ever picks
# from a known set. Naming them here beats dropping a row the theme lays out
# against — wps_item is the top of the main menu.
DYNTEXT = {
    "wps_item": "LANG_RESUME_PLAYBACK",     # LANG_NOW_PLAYING while something plays
}

# Icon ids beyond Icon_Last_Themeable come from the theme's viewers iconset —
# apps-ipod/files/filetypes.c pins the two the firmware itself hands out.
VIEWER_TXT = len(ICON_NAMES)                # Icon_Last_Themeable + 1
VIEWER_IMG = len(ICON_NAMES) + 1            # Icon_Last_Themeable + 2

# The browsers build their lists from what is on the disk, so there is nothing
# in the source to read. These are fixtures — plausible contents with the icon
# ids the firmware really assigns, which is the part a row layout branches on.
BROWSERS = [
    {"screen": 7, "name": "File browser", "title": "Files", "titleIcon": ICONS["Icon_file_view_menu"],
     "rows": [("Albums", "Icon_Folder"), ("Playlists", "Icon_Folder"),
              ("01 Nightcall.flac", "Icon_Audio"), ("02 Odd Look.flac", "Icon_Audio"),
              ("Nightcall.m3u8", "Icon_Playlist"), ("liner-notes.txt", VIEWER_TXT),
              ("cover.jpg", VIEWER_IMG), ("Themify_2.cfg", "Icon_Config"),
              ("22-Literata.fnt", "Icon_Font"), ("resume.bmark", "Icon_Bookmark")]},
    {"screen": 8, "name": "Database — top", "title": "Music", "titleIcon": ICONS["Icon_Audio"],
     "rows": [("Artist", "Icon_Audio"), ("Album Artist", "Icon_Audio"),
              ("Album", "Icon_Audio"), ("Genre", "Icon_Audio"), ("Composer", "Icon_Audio"),
              ("Year", "Icon_Audio"), ("Track", "Icon_Audio"), ("Search by...", "Icon_Audio"),
              ("Recently Added", "Icon_Audio"), ("User Rating", "Icon_Audio")]},
    {"screen": 8, "name": "Database — albums", "title": "Album", "titleIcon": ICONS["Icon_Audio"],
     "rows": [("OutRun", "Icon_Audio"), ("Kavinsky EP", "Icon_Audio"),
              ("Nightcall EP", "Icon_Audio"), ("Reborn", "Icon_Audio"),
              ("Drive (Original Motion Picture Soundtrack)", "Icon_Audio")]},
    {"screen": 5, "name": "Playlist viewer", "title": "Current Playlist",
     "titleIcon": ICONS["Icon_Playlist"],
     "rows": [("01 Nightcall", "Icon_Audio"), ("02 Odd Look", "Icon_Audio"),
              ("03 Protovision", "Icon_Queued"), ("04 Rampage", "Icon_Audio"),
              ("05 Blizzard", "Icon_Moving")]},
    {"screen": 15, "name": "Context menu", "title": "Context Menu",
     "titleIcon": ICONS["Icon_Submenu"],
     "rows": [("Playlist", "Icon_Playlist"), ("Add to Shortcuts", "Icon_Bookmark"),
              ("Open With", "Icon_Plugin"), ("Delete", "Icon_NOICON"),
              ("Rename", "Icon_NOICON"), ("Set As Backdrop", "Icon_Wps"),
              ("Properties", "Icon_NOICON")]},
    {"screen": 22, "name": "Album covers", "title": "Album Covers",
     "titleIcon": ICONS["Icon_Folder"],
     "rows": [("OutRun — Kavinsky", "Icon_Audio"), ("Reborn — Kavinsky", "Icon_Audio"),
              ("Drive — Various Artists", "Icon_Audio"), ("Random Access Memories — Daft Punk", "Icon_Audio")]},
    {"screen": 25, "name": "Folder select", "title": "Select Folder",
     "titleIcon": ICONS["Icon_Folder"],
     "rows": [("Music", "Icon_Folder"), ("Podcasts", "Icon_Folder"),
              ("Audiobooks", "Icon_Folder"), ("Recordings", "Icon_Folder")]},
    {"screen": 19, "name": "Shortcuts", "title": "Shortcuts",
     "titleIcon": ICONS["Icon_Bookmark"],
     "rows": [("Music", "Icon_Folder"), ("Shuffle Songs", "Icon_Playlist"),
              ("Sleep Timer", "Icon_Menu_setting"), ("Brightness", "Icon_Menu_setting")]},
]


def icon_value(text):
    """An icon argument: a name, or Icon_Last_Themeable + n for a viewer icon."""
    text = (text or "").strip()
    m = re.match(r"^(Icon_\w+)\s*\+\s*(\d+)$", text)
    if m:
        base = ICONS.get(m.group(1))
        return None if base is None else base + int(m.group(2))
    return ICONS.get(text)


# ---------------------------------------------------------------- lang

def read_lang(path):
    """LANG_* -> the <dest> English string. The file is the master source for
    every language, so <dest> under english.lang is the English text."""
    out = {}
    ident, section, dest = None, None, None
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            s = line.strip()
            if s.startswith("<phrase>"):
                ident, section, dest = None, None, None
            elif s.startswith("id:"):
                ident = s[3:].strip()
            elif s in ("<dest>", "<source>", "<voice>"):
                section = s
            elif s.startswith("</"):
                section = None
            elif section == "<dest>" and ident and ":" in s:
                # `*: "Settings"`, or a target-specific override before it
                val = s.split(":", 1)[1].strip()
                if val.startswith('"') and val.endswith('"') and len(val) >= 2:
                    if dest is None:                 # the first wins: `*:` leads
                        dest = val[1:-1]
                        out[ident] = dest
    return out


# ------------------------------------------------------------ C parsing

def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


def split_args(text):
    """Top-level commas only — arguments contain calls and casts of their own."""
    args, depth, cur = [], 0, ""
    for ch in text:
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        if ch == "," and depth == 0:
            args.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        args.append(cur.strip())
    return args


def find_macros(text, name):
    """Every `name(...)` in the file, with its balanced argument list."""
    out = []
    for m in re.finditer(r"\b" + re.escape(name) + r"\s*\(", text):
        i, depth = m.end() - 1, 0
        while i < len(text):
            if text[i] == "(":
                depth += 1
            elif text[i] == ")":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        if i < len(text):
            out.append(split_args(text[m.end():i]))
    return out


def lang_of(arg):
    m = re.search(r"ID2P\s*\(\s*(LANG_\w+)\s*\)", arg or "")
    return m.group(1) if m else None


def read_settings_langs(root):
    """setting variable -> LANG_*, so a MENUITEM_SETTING can be named.

    Every shape in settings_list.c puts the variable second and its display
    string third — `OFFON_SETTING(0, sort_case, LANG_SORT_CASE, ...)` — and a
    MENUITEM_SETTING names the same variable, so the two meet on that name.
    Settings with no string of their own (the SYSTEM_SETTING block) simply do
    not appear here, which is right: they are not menu rows."""
    out = {}
    path = os.path.join(root, "apps-ipod", "settings", "settings_list.c")
    if not os.path.isfile(path):
        return out
    text = strip_comments(open(path, encoding="utf-8", errors="replace").read())
    for m in re.finditer(r"\b(\w*_SETTING)\s*\(", text):
        i, depth = m.end() - 1, 0
        while i < len(text):
            if text[i] == "(":
                depth += 1
            elif text[i] == ")":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        args = split_args(text[m.end():i])
        if len(args) < 3:
            continue
        var = re.match(r"^&?(?:global_settings\.)?(\w+)$", args[1].strip())
        lang = re.match(r"^(LANG_\w+)$", args[2].strip())
        if var and lang and var.group(1) not in out:
            out[var.group(1)] = lang.group(1)
    return out


ITEM_SHAPES = {
    # macro name                    -> (index of the text arg, index of the icon arg)
    "MENUITEM_RETURNVALUE":            (1, 4),
    "MENUITEM_FUNCTION":               (2, 5),
    "MENUITEM_FUNCTION_W_PARAM":       (2, 6),
    "MENUITEM_STRINGLIST":             (1, None),
    "MENUITEM_SETTING_W_TEXT":         (2, None),
}


def collect(root):
    items, menus = {}, {}
    setting_langs = read_settings_langs(root)
    base = os.path.join(root, "apps-ipod")

    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = [d for d in dirnames if d not in (".git", "sim")]
        for fn in filenames:
            if not fn.endswith(".c"):
                continue
            path = os.path.join(dirpath, fn)
            text = strip_comments(open(path, encoding="utf-8", errors="replace").read())
            where = os.path.relpath(path, root).replace(os.sep, "/")

            for macro, (text_i, icon_i) in ITEM_SHAPES.items():
                for args in find_macros(text, macro):
                    if len(args) <= text_i:
                        continue
                    name = args[0].strip()
                    items[name] = {
                        "lang": lang_of(args[text_i]),
                        "icon": icon_value(args[icon_i]) if icon_i is not None
                                and len(args) > icon_i else None,
                        "from": where,
                    }

            # A setting row is named by the setting, not by the menu entry.
            for macro in ("MENUITEM_SETTING", "MENUITEM_SETTING_EXPORTED"):
                for args in find_macros(text, macro):
                    if len(args) < 2:
                        continue
                    var = re.search(r"(?:global_settings\.)?(\w+)\s*$", args[1].strip())
                    name = args[0].strip()
                    if name in items and items[name].get("lang"):
                        continue         # a W_TEXT form already named it
                    items[name] = {
                        "lang": setting_langs.get(var.group(1)) if var else None,
                        "icon": None, "from": where,
                    }

            # Text decided at runtime: keep the item so the tree stays whole,
            # and name it where the firmware only picks from a known set.
            for macro in ("MENUITEM_RETURNVALUE_DYNTEXT", "MENUITEM_FUNCTION_DYNTEXT"):
                for args in find_macros(text, macro):
                    name = args[0].strip()
                    items[name] = {
                        "lang": DYNTEXT.get(name),
                        "dynamic": name not in DYNTEXT,
                        "icon": icon_value(args[-1]) if args else None,
                        "from": where,
                    }

            for args in find_macros(text, "MAKE_MENU"):
                if len(args) < 4:
                    continue
                name = args[0].strip()
                menus[name] = {
                    "lang": lang_of(args[1]),
                    "icon": icon_value(args[3]),
                    "items": [a.strip().lstrip("&") for a in args[4:]],
                    "from": where,
                }
    return items, menus, setting_langs


def root_menu_order(root):
    """root_menu.c settles the root menu's order at runtime, in one function.
    Its two arrays are the order, with the tagnavi rows in between."""
    path = os.path.join(root, "apps-ipod", "root_menu.c")
    if not os.path.isfile(path):
        return []
    text = strip_comments(open(path, encoding="utf-8", errors="replace").read())
    out = []
    for which in ("before_tagnavi", "after_tagnavi"):
        m = re.search(re.escape(which) + r"\s*\[\s*\]\s*=\s*\{(.*?)\}", text, re.S)
        if m:
            out.append([n.strip().lstrip("&") for n in m.group(1).split(",") if n.strip()])
        else:
            out.append([])
    return out[0] + out[1]


# ------------------------------------------------------------- assembly

def build(root):
    lang = read_lang(os.path.join(root, "apps-ipod", "lang", "english.lang"))
    items, menus, _ = collect(root)

    def text_of(entry, fallback):
        if entry.get("dynamic"):
            return None
        ident = entry.get("lang")
        return lang.get(ident) if ident else (None if ident else fallback)

    def rows_for(names):
        rows = []
        for name in names:
            entry = items.get(name) or menus.get(name)
            if not entry:
                continue
            label = text_of(entry, None)
            if label is None:
                continue                       # dynamic, or a string we cannot resolve
            icon = entry.get("icon")
            if name in menus and icon is None:
                icon = ICONS["Icon_Submenu"]
            rows.append({"text": label, "icon": icon if icon is not None else -1})
        return rows

    out = []

    order = root_menu_order(root)
    if order:
        out.append({
            "screen": ACTIVITY["MAINMENU"], "title": lang.get("LANG_ROCKBOX_TITLE", "Rockbox"),
            "name": "Main menu", "titleIcon": ICONS["Icon_Rockbox"],
            "rows": rows_for(order), "from": "apps-ipod/root_menu.c",
        })

    # Every menu reachable from Settings is drawn while ACTIVITY_SETTINGS is on
    # top; the system screen and the context menu have activities of their own.
    roots = [("main_menu_", ACTIVITY["SETTINGS"]),
             ("info_menu", ACTIVITY["SYSTEMSCREEN"])]
    seen = set()
    queue = [(n, s) for n, s in roots if n in menus]
    while queue:
        name, screen = queue.pop(0)
        if name in seen:
            continue
        seen.add(name)
        menu = menus[name]
        rows = rows_for(menu["items"])
        if rows:
            out.append({
                "screen": screen,
                "title": lang.get(menu["lang"], name) if menu["lang"] else name,
                "name": lang.get(menu["lang"], name) if menu["lang"] else name,
                "titleIcon": menu["icon"] if menu["icon"] is not None else -1,
                "rows": rows, "from": menu["from"],
            })
        for child in menu["items"]:
            if child in menus:
                queue.append((child, screen))

    for fixture in BROWSERS:
        out.append({
            "screen": fixture["screen"], "title": fixture["title"],
            "name": fixture["name"], "titleIcon": fixture["titleIcon"],
            "fixture": True, "from": "hand-written; icon ids from icon.h",
            "rows": [{"text": t,
                      "icon": ICONS[i] if isinstance(i, str) else i}
                     for t, i in fixture["rows"]],
        })

    out.sort(key=lambda e: (e["screen"], e["name"].lower()))
    return out, lang


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("firmware", nargs="?", default=DEFAULT_FIRMWARE,
                    help="the firmware checkout to read (default: the one this "
                         "script lives in)")
    ap.add_argument("--js", action="store_true", help="emit a JS literal, not JSON")
    ap.add_argument("-o", "--out", help="write here as UTF-8 rather than to stdout — "
                                        "a shell redirect can mangle the text on Windows")
    ap.add_argument("--embed", metavar="INDEX_HTML",
                    help="replace the FIRMWARE_LISTS block in this file in place")
    ap.add_argument("--max-rows", type=int, default=40,
                    help="drop rows past this many — a fixture, not an archive")
    args = ap.parse_args()

    root = os.path.abspath(args.firmware)
    if not os.path.isdir(os.path.join(root, "apps-ipod")):
        sys.exit("no apps-ipod/ under %s — is that the firmware checkout?" % root)

    lists, lang = build(root)
    for entry in lists:
        del entry["from"]
        entry["rows"] = entry["rows"][:args.max_rows]

    rows = sum(len(e["rows"]) for e in lists)
    sys.stderr.write("%d lists, %d rows, %d phrases\n" % (len(lists), rows, len(lang)))

    def emit(text):
        if args.out:
            with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(text + "\n")
            sys.stderr.write("wrote %s\n" % args.out)
        else:
            print(text)

    if not (args.js or args.embed):
        emit(json.dumps(lists, indent=1, ensure_ascii=False))
        return

    # The embedded form: a row is "text" or "text|icon", which is exactly what
    # the State pane's rows box takes, so applying a preset is a paste.
    compact = [{
        "s": e["screen"], "n": e["name"], "t": e["title"], "ti": e["titleIcon"],
        "f": 1 if e.get("fixture") else 0,
        # -1 is Icon_NOICON — a row that draws no icon, which is not the same
        # as a row that did not say, so it is written out rather than omitted.
        "r": [r["text"] + ("|%d" % (r["icon"] if r["icon"] is not None else -1))
              for r in e["rows"]],
    } for e in lists]
    block = "\n".join([
        BLOCK_MARKER + " from the firmware sources.",
        "   Re-run it rather than editing this by hand:",
        "     python tools/theme-lens/extract-lists.py --embed index.html",
        "   %d lists, %d rows. Entries with f:1 are hand-written fixtures — the" % (len(lists), rows),
        "   browsers build their lists from the disk, so there is nothing in the",
        "   source to read; only their icon ids come from icon.h. */",
        "const FIRMWARE_LISTS = " + json.dumps(compact, ensure_ascii=False,
                                               separators=(",", ":")) + ";",
    ])

    if not args.embed:
        emit(block)
        return

    with open(args.embed, encoding="utf-8") as fh:
        html = fh.read()
    # Find the old block by the declaration it makes, not by the wording of the
    # comment above it. Matching on the comment meant that changing that wording
    # -- moving the script, so the path in it moved -- stopped --embed
    # recognising its own output: it took the "none there" branch and appended a
    # second block, and two `const FIRMWARE_LISTS` in a row is a syntax error
    # that kills the page. Keyed this way there is nothing left to drift.
    #
    # Every occurrence goes, not just the first, so one run also repairs a file
    # that already collected a duplicate.
    key = "const FIRMWARE_LISTS = "
    at = None

    while key in html:
        start = html.index(key)
        head = html[:start].rstrip()
        if head.endswith("*/"):                 # swallow the comment above it
            opened = head.rfind("/*")
            if opened >= 0:
                start = opened
        end = html.index("\n", html.index(key)) + 1
        if at is None:
            at = start                          # put the new one back here
        html = html[:start] + html[end:]

    if at is None:
        anchor = "const LCD_W = 320, LCD_H = 240;"
        if anchor not in html:
            sys.exit("nowhere to put it: %s has no FIRMWARE_LISTS block and no %r"
                     % (args.embed, anchor))
        at = html.index(anchor)
        block += "\n"

    html = html[:at] + block + "\n" + html[at:]
    with open(args.embed, "w", encoding="utf-8", newline="") as fh:
        fh.write(html)
    sys.stderr.write("embedded into %s\n" % args.embed)


if __name__ == "__main__":
    main()
