/***************************************************************************
 * Original code from RockBox
 * was: apps/language.c
 * Copyright (C) 2002 Daniel Stenberg
 * GNU General Public License (version 2+)
 *
 * Loads a translated .lng file over the built-in strings, and reports text
 * direction for right-to-left languages.
 ****************************************************************************/

#include <stdio.h>
#include "file.h"

#include "language.h"
#include "lang.h"
#include "debug.h"
#include "string.h"
#include "draw/viewport.h"

/* The following header is generated by the build system and only defines
   MAX_LANGUAGE_SIZE to be the size of the largest currently available
   language! */
#include "max_language_size.h"

/* These defines must match the initial bytes in the binary lang file */
/* See tools/genlang (TODO: Use common include for both) */
#define LANGUAGE_COOKIE   0x1a
#define LANGUAGE_VERSION  0x06

#define LANGUAGE_FLAG_RTL         0x01
#define LANGUAGE_FLAG_UNITS_FIRST 0x02

#define HEADER_SIZE 4
#define SUBHEADER_SIZE 6

static unsigned char language_buffer[MAX_LANGUAGE_SIZE];
static unsigned char lang_options = 0;

/* Bytes of language_buffer holding the loaded .lng; the rest is spare and
 * lang_override.c writes there. Only ever set on the path that fills the
 * buffer -- a load that fails leaves the previous language in place, and the
 * pointers into it still live. */
static int language_buffer_used = 0;

void lang_init(const unsigned char *builtin, unsigned char **dest, int count)
{
    while(count--) {
        *dest++ = (unsigned char *)builtin;
        /* advance pointer to next string */
        builtin += strlen((char *)builtin) + 1;
    }
}

int lang_load(const char *filename, const unsigned char *builtin,
              unsigned char **dest, unsigned char *buffer,
              unsigned int user_num, int max_lang_size,
              unsigned int max_id)
{
    int lang_size;
    int fd = open(filename, O_RDONLY);
    int retcode=0;
    unsigned char lang_header[HEADER_SIZE];
    unsigned char sub_header[SUBHEADER_SIZE];
    unsigned int id, foffset;

    if(fd < 0)
        return 1;

    if(read(fd, lang_header, HEADER_SIZE) == HEADER_SIZE &&
       ((lang_header[0] == LANGUAGE_COOKIE) &&
       (lang_header[1] == LANGUAGE_VERSION) &&
       (lang_header[2] == TARGET_ID))) {
        /* jump to the proper entry in the table of subheaders */
        lseek(fd, user_num * SUBHEADER_SIZE, SEEK_CUR);
        if (read(fd, sub_header, SUBHEADER_SIZE) != SUBHEADER_SIZE)
        {
            DEBUGF("Language %s bad subheader %u\n", filename, user_num);
            retcode = 4;
        }
        /* read in information about the requested lang */
        /* sub_header[0..1] is a big-endian string count, not read here. */
        lang_size = (sub_header[2]<<8) | sub_header[3];
        foffset = (sub_header[4]<<8) | sub_header[5];
        if(lang_size <= max_lang_size) {
            /* initialize with builtin */
            lang_init(builtin, dest, max_id);
            lseek(fd, foffset, SEEK_SET);
            read(fd, buffer, lang_size);
            buffer[max_lang_size - 1] = '\0'; /* ensure buffer is null terminated */
            language_buffer_used = lang_size; /* before the walk consumes it */
            while(lang_size>3) {
                id = ((buffer[0]<<8) | buffer[1]); /* get two-byte id */
                buffer += 2;                       /* pass the id */
                if(id < max_id) {
                    dest[id] = buffer; /* point to this string */
                }
                while(*buffer) {               /* pass the string */
                    lang_size--;
                    buffer++;
                }
                lang_size-=3; /* the id and the terminating zero */
                buffer++;     /* pass the terminating zero-byte */
            }
        }
        else {
            DEBUGF("Language %s too large: %d\n", filename, lang_size);
            retcode = 2;
        }
    }
    else {
        DEBUGF("Illegal language file\n");
        retcode = 3;
    }
    close(fd);
    lang_options = retcode ? 0 : lang_header[3];
    return retcode;
}

int lang_core_load(const char *filename)
{
    return lang_load(filename, core_language_builtin, language_strings,
                     language_buffer, 0, MAX_LANGUAGE_SIZE,
                     LANG_LAST_INDEX_IN_ARRAY);
}

/* The unused tail of the language buffer. With no .lng loaded that is all of
   it, around 27KB. */
unsigned char *lang_spare_buffer(int *size)
{
    *size = MAX_LANGUAGE_SIZE - language_buffer_used;
    return language_buffer + language_buffer_used;
}

/* Eighteen english strings are used by two phrases each, so a caller that
   wants all of them resumes the scan rather than stopping at the first. */
int lang_english_to_id_from(const char *english, int start_id)
{
    int i;
    unsigned char *ptr = (unsigned char *) core_language_builtin;
    size_t ptrlen, len = strlen(english);
    for (i = 0; i < LANG_LAST_INDEX_IN_ARRAY; i++) {
        ptrlen = strlen((char *)ptr);
        if ((i >= start_id) && (ptrlen == len) &&
            memcmp(ptr, english, ptrlen) == 0)
            return i;
        ptr += ptrlen + 1; /* advance pointer to next string */
    }
    return -1;
}

int lang_english_to_id(const char *english)
{
    return lang_english_to_id_from(english, 0);
}

/* Settings that store a lang id must write the english string, not the
   translated one, or the value stops resolving when the language changes. */
const char *lang_id_to_english(int lang_id)
{
    int i;
    unsigned char *ptr = (unsigned char *) core_language_builtin;

    if (lang_id >= 0 && lang_id < LANG_LAST_INDEX_IN_ARRAY)
    {
        if (language_strings[0] == ptr) /* already in english */
            return str(lang_id);

        for (i = 0; i < LANG_LAST_INDEX_IN_ARRAY; i++) {
            if (i == lang_id)
                return (char *)ptr;
            ptr += strlen((char *)ptr) + 1; /* advance pointer to next string */
        }
    }
    return ""; /* Not found */
}

int lang_is_rtl(void)
{
    return (lang_options & LANGUAGE_FLAG_RTL) != 0;
}

int lang_units_first(void)
{
    return (lang_options & LANGUAGE_FLAG_UNITS_FIRST) != 0;
}
